import React, { useState, useEffect } from 'react';
import { collection, getDocs } from 'firebase/firestore';
import { firestore } from '../../../utils/firebase';


function sortByAppliedDate(
  array, sortOrder = 'desc'
) {
  return array.sort((a, b) => {
    const dateA = new Date(a.appliedDate);
    const dateB = new Date(b.appliedDate);

    if (sortOrder === 'asc') {
      return dateA.getTime() - dateB.getTime(); // Sort ascending (oldest first)
    } else {
      return dateB.getTime() - dateA.getTime(); // Sort descending (latest first)
    }
  });
}

const TrackingLinksTable = () => {
  const [trackingLinks, setTrackingLinks] = useState([]);
  const [isLoading, setIsloading] = useState(true);

  useEffect(() => {
    const fetchTrackingLinks = async () => {
      try {
        setIsloading(true);
        const querySnapshot = await getDocs(collection(firestore, "impactTrackingLinksDev"));
        const links = querySnapshot.docs.map(doc => ({
          id: doc.id,
          ...doc.data(),
          appliedDate: new Date(doc.data().appliedDate.seconds * 1000 + doc.data().appliedDate.nanoseconds / 1000000).toLocaleString()
        }));

        const sorted = sortByAppliedDate(links);
        setTrackingLinks(sorted);
        setIsloading(false);
      } catch (error) {
        console.error('Error fetching tracking links:', error);
        setIsloading(false);
      }
    };

    fetchTrackingLinks();
  }, []);


  if(isLoading) return (<p>loading</p>)

  return (
    <div className="container w-full m-3">
      <h1>Impact Tracking Links</h1>
      <table className="table table-striped table-bordered">
        <thead className="thead-dark">
          <tr>
            <th>Applied Date</th>
            <th>Link Initially Generated By</th>
            <th>Program ID</th>
            <th>Team Name</th>
            <th>Impact Tracking Link</th>
          </tr>
        </thead>
        <tbody>
          {trackingLinks.map(link => (
            <tr key={link.id}>
              <td>{link.appliedDate}</td>
              <td>{link.linkInitiallyGeneratedBy}</td>
              <td>{link.programId}</td>
              <td>{link.teamName}</td>
              <td>{link.trackingLink}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default TrackingLinksTable;
